### PRODUCTS ENDPOINTS
### create products to see 
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "design intensive data Application 3",
    "description": "book for software design",
    "price": 300,
    "stock": 100,
    "productCategory": "software book"
}


### See all products
GET http://localhost:3000/products


### See one product

GET http://localhost:3000/products/6784695134af3c406ad6acb0



### SHOPPING CART ENDPOINTS
@userId = 67813c177b853239eb1cebac
### add products to cart



POST http://localhost:3000/cart/{{userId}}/add
Content-Type: application/json

{ 
    "items": [
        
        { "productId": "678610452930aa6cd01ed86a", "quantity": 2 }
       
    ]
}
   


### see all products in cart for userId

GET http://localhost:3000/cart/{{userId}}


### remove all especific products from cart by id
DELETE  http://localhost:3000/cart/{{userId}}/remove/6785f6660ac8051433a91aed


### deacrease quantity products from cart
PATCH  http://localhost:3000/cart/{{userId}}/decrease/6785f6660ac8051433a91aed?quantity=1

### PURCHASE ENDPOINTS 

### checkout products in cart
POST http://localhost:3000/purchase/{{userId}}/checkout


### statistics of purchases

GET http://localhost:3000/purchase/{{userId}}/statistics
