version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=mongodb://quero:delivery@db:27017/shopping-cart?authSource=admin
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: quero
      MONGO_INITDB_ROOT_PASSWORD: delivery
    ports:
      - "27017:27017"
    

  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_test
    command: /bin/bash -c "npm install && npm run test -- --verbose && npm run test:e2e -- --verbose"
    environment:
      - DATABASE_URL=mongodb://quero:delivery@db:27017/shopping-cart-test?authSource=admin
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
 


